### ISSUE TITLE
`:report-output` is specced as a set but the default value is a keyword

### ISSUE THREAD

**Issue by thenonameguy** [gnl/ghostwheel#19]
Spec: https://github.com/gnl/ghostwheel/blob/3ef7e08aa8508210ab9b0dc4817e7c236bad9646/src/ghostwheel/core.cljc#L127

Default:
https://github.com/gnl/ghostwheel/blob/3ef7e08aa8508210ab9b0dc4817e7c236bad9646/src/ghostwheel/utils.cljc#L95

**Comment by thenonameguy** [comment]
I would also argue that the `:distinct true` part is unnecessary in the spec, since the `:kind` is already a set.

**Comment by gnl** [comment]
Good catch, thanks! Will fix this in the next minor release.

**Comment by gnl** [comment]
Fixed in https://github.com/gnl/ghostwheel/commit/df1a7d81d1ec5ed3ffc406b7a99bc4125bfe63e0
