### ISSUE TITLE
Spec assertion failed\n:js-console - failed: set?

### ISSUE THREAD

**Issue by mjmeintjes** [gnl/ghostwheel#22]
Every now and the I get the following error when evaluating a function:

Spec assertion failed\n:js-console - failed: set? in: [:ghostwheel.core/report-output]

It seems to fix itself when I restart the repl.

This is in clojure files with the following header:
```
  #:ghostwheel.core{:check false :num-tests 10 :outstrument true}
```

It also gets fixed when I add `:report-output #{:repl}` to the config.

**Comment by gnl** [comment]
Related to #19 – should be fixed in https://github.com/gnl/ghostwheel/commit/df1a7d81d1ec5ed3ffc406b7a99bc4125bfe63e0 , reopen if not!
