### ISSUE TITLE
Linking to cljdocs

### ISSUE THREAD

**Issue by l3nz** [gnl/ghostwheel#3]
Hi,
this library looks wonderful :-) and I see it's referenced on https://cljdoc.xyz/d/gnl/ghostwheel/0.2.2/doc/readme

Why don't you add a badge to the docs? 

[![](https://cljdoc.xyz/badge/gnl/ghostwheel)](https://cljdoc.xyz/jump/release/gnl/ghostwheel)

``````
[![](https://cljdoc.xyz/badge/gnl/ghostwheel)](https://cljdoc.xyz/jump/release/gnl/ghostwheel)
``````

**Comment by gnl** [comment]
That's great! I've actually been looking into API doc generators and now that's taken care of. I'll see about setting things up to remove some of the noise from the generated docs, but that's a topic for another day.

**Comment by martinklepsch** [comment]
Thanks for opening this issue @l3nz, opening these kinds issues will go a long way in improving cljdoc adoption ❤️ 

@gnl, if you want to remove some namespaces from the list, just add `:no-doc` metadata [as you would do in Codox](https://github.com/weavejester/codox#metadata-options). Hope this helps and let me know if you have any other questions :)

**Comment by gnl** [comment]
@martinklepsch This definitely helps and is exactly what I would have googled first when tacking this particular issue. :)
