### ISSUE TITLE
Test on CircleCI ?

### ISSUE THREAD

**Issue by marco-m** [gnl/ghostwheel#7]
hello,

would you be interested in a PR to run on CircleCI (similar to Travis, see how it looks like at https://circleci.com/gh/marco-m/etaoin) ?

**Comment by gnl** [comment]
Hey Marco,
totally! Setting things up with CircleCI has been relatively high up on the Ghostwheel todo list, but I haven't had time to look into it yet.

**Comment by gnl** [comment]
Just a quick note – if you do the PR please make sure that all tests in all environments from the `run-all-tests.sh` script are being executed.

**Comment by marco-m** [comment]
yes I was looking at that script file right now :-)
